<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{46bc1a8e-e556-49ad-b470-22cd57fcf0b2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
XtsProgram();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="221" Count="0" />
      <LineId Id="74" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>