<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="XtsAxis" Id="{ec1eec99-a289-419f-92b9-8b98742473d8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK XtsAxis
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR

	Axis			: AXIS_REF;
	
	BusyMoving				: BOOL;
	BusyStopping			: BOOL;
	Error					: BOOL;
	ErrorID					: UDINT;
	ErrorIDPrevious			: UDINT;
	ErrorStop				: BOOL;
	Disabled				: BOOL;
	Stopping				: BOOL;
	StandStill				: BOOL;
	DiscreteMotion			: BOOL;
	ContinuousMotion		: BOOL;
	SynchronizedMotion		: BOOL;
	Homing					: BOOL;
	ConstantVelocity		: BOOL;
	Accelerating			: BOOL;
	Decelerating			: BOOL;
	Status					: ST_AxisStatus;
	ErrorCount				: UINT;

END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Fbd"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">9L</v>
                </o>
              </l2>
              <v n="BranchCounter">1</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Folder Name="Movements" Id="{e983c8f8-8927-4dc9-9aed-b49726e466f0}" />
    <Folder Name="Power and Utility" Id="{27299485-0fb2-48d8-a5a9-eb5b18706a1b}" />
  </POU>
</TcPlcObject>